var category = [
    {"id": "nature", "name": "自然"},
    {"id": "season", "name": "季節"},
    {"id": "life", "name": "生活"},
    {"id": "building", "name": "建物"},
    {"id": "railway", "name": "鉄道"},
]

var photo = {
    "nature": [
        { "id": "p5", "desc": "Kamogawa, Kyoto / 京都鴨川" },
        { "id": "p48", "desc": "Kamogawa, Kyoto / 京都鴨川" },
        { "id": "p6", "desc": "Angel's Road, Shodoshima / 小豆島エンジェルロード" },
        { "id": "p11", "desc": "Seto Naikai / 瀬戸内海" },
        { "id": "p12", "desc": "Seto Naikai / 瀬戸内海" },
        { "id": "p17", "desc": "Kamakura / 鎌倉" },
        { "id": "p19", "desc": "Amanohashidate, Kyoto-fu / 京都府天橋立" },
        { "id": "p21", "desc": "Uji River / 宇治川" },
        { "id": "p22", "desc": "Kankakei, Shodoshima / 小豆島寒霞渓" },
        { "id": "p33", "desc": "Seto Naikai / 瀬戸内海" },
        { "id": "p35", "desc": "Asamayama, Karuizawa / 軽井沢浅間山" },
        { "id": "p66", "desc": "Hijikawa, Ozu / 大洲市肱川" },
    ],
    "season": [
        { "id": "p2", "desc": "Kenchoji, Kamakura / 鎌倉建長寺" },
        { "id": "p59", "desc": "Kenchoji, Kamakura / 鎌倉建長寺" },
        { "id": "p4", "desc": "Tofukuji, Kyoto / 京都東福寺" },
        { "id": "p70", "desc": "Tofukuji, Kyoto / 京都東福寺" },
        { "id": "p14", "desc": "Jojakkoji, Kyoto / 京都常寂光寺" },
        { "id": "p16", "desc": "Ritsurin Park, Takamatsu / 高松栗林公園" },
        { "id": "p32", "desc": "Tsurugaoka, Kamakura / 鎌倉鶴岡" },
        { "id": "p56", "desc": "Meigetsu-in, Kamakura / 鎌倉明月院" },
        { "id": "p49", "desc": "Eikando, Kyoto / 京都永観堂" },
        { "id": "p51", "desc": "Kiyomizutera, Kyoto / 京都清水寺" },
        { "id": "p52", "desc": "Tenryuji, Kyoto / 京都天龍寺" },
        { "id": "p61", "desc": "Ueno Park, Tokyo / 東京上野公園" },
        { "id": "p65", "desc": "Kotoku-in, Kamakura / 鎌倉高徳院" },
    ],
    "life": [
        { "id": "p63", "desc": "Shinjuku Gyoen, Tokyo / 東京新宿御苑" },
        { "id": "p25", "desc": "Akihabara, Tokyo / 東京秋葉原" }, 
        { "id": "p27", "desc": "Ine boat house, Kyoto / 京都伊根船屋" },
        { "id": "p30", "desc": "Dotonbori, Osaka / 大阪道頓堀" },
        { "id": "p39", "desc": "Kichijoji, Musashino / 武蔵野吉祥寺" },
        { "id": "p41", "desc": "Shinjuku, Tokyo / 東京新宿" },
        { "id": "p42", "desc": "Shinsaibashi, Osaka / 大阪心斎橋" },
        { "id": "p47", "desc": "Teramachi, Kyoto / 京都寺町" },
        { "id": "p68", "desc": "Asakusa, Tokyo / 東京淺草" },
        { "id": "p62", "desc": "Asakusa, Tokyo / 東京淺草" },
    ],
    "building": [
        { "id": "p1", "desc": "Tokyo Tower / 東京タワー" },
        { "id": "p3", "desc": "Shinkyo Bridge, Nikko / 日光神橋" },
        { "id": "p7", "desc": "Shinjuku Gyoen, Tokyo / 東京新宿御苑" },
        { "id": "p8", "desc": "Byodoin, Uji / 宇治平等院" },
        { "id": "p45", "desc": "Byodoin, Uji / 宇治平等院" },
        { "id": "p9", "desc": "Tsutenya, Osaka / 大阪通天閣" },
        { "id": "p10", "desc": "Kasuga Taisha, Nara / 奈良春日大社" },
        { "id": "p55", "desc": "Kasuga Taisha, Nara / 奈良春日大社" },
        { "id": "p13", "desc": "Tokyo / 東京" },
        { "id": "p15", "desc": "Osaka / 大阪" },
        { "id": "p18", "desc": "Kotoku-in, Kamakura / 鎌倉高徳院" },
        { "id": "p23", "desc": "Kyoto Tower / 京都タワー" },
        { "id": "p24", "desc": "Kobe Harbour / 神戸港" },
        { "id": "p29", "desc": "Torii of Heian Jingu, Kyoto / 京都平安神宮の鳥居" },
        { "id": "p34", "desc": "Kurushima Kaikyo Ohashi, Imabari / 今治来島海峡大橋" },
        { "id": "p36", "desc": "Toshogu, Nikko / 日光東照宮" },
        { "id": "p57", "desc": "Ritsurin Park, Takamatsu / 高松栗林公園" },
        { "id": "p58", "desc": "Ritsurin Park, Takamatsu / 高松栗林公園" },
        { "id": "p67", "desc": "Inokashira Onshi Koen / 井の頭恩賜公園" },
        { "id": "p69", "desc": "Osaka Castle Park / 大阪城公園" },
        { "id": "p71", "desc": "Fushimi Inari Taisha, Kyoto / 京都伏見稲荷大社" },
        { "id": "p72", "desc": "Takamatsu Castle / 高松城" },
    ],
    "railway": [
        { "id": "p20", "desc": "Ochanomizu, Tokyo / 東京御茶ノ水" },
        { "id": "p26", "desc": "Enoden Train, Kamakura / 鎌倉江ノ電" },
        { "id": "p28", "desc": "Baishinji Station, Matsuyama / 松山梅津寺駅" },
        { "id": "p40", "desc": "Keio Line, Kichijoji / 吉祥寺の京王線" },
        { "id": "p44", "desc": "Inside JR Nara Line / JR奈良線の列車の中" },
        { "id": "p46", "desc": "JR Kyoto Station / JR京都駅" },
        { "id": "p50", "desc": "Fushimiinari Station / 伏見稲荷駅" },
        { "id": "p53", "desc": "Arashiyama, Kyoto / 京都嵐山" },
    ],
}
