var descTitle = [
    "",
    "Tokyo Tower / 東京タワー",
    "Kenchoji, Kamakura / 鎌倉建長寺",
    "Shinkyo Bridge, Nikko / 日光神橋",
    "Tofukuji, Kyoto / 京都東福寺",
    "Kamogawa, Kyoto / 京都鴨川",
    "Angel&apos;s Road, Shodoshima / 小豆島エンジェルロード",
    "Shinjuku Gyoen, Tokyo / 東京新宿御苑",
    "Byodoin, Uji / 宇治平等院",
    "Tsutenya, Osaka / 大阪通天閣",
    "Kasuga Taisha, Nara / 奈良春日大社",
    "Seto Naikai / 瀬戸内海",
    "Seto Naikai / 瀬戸内海",
    "Tokyo / 東京",
    "Jojakkoji, Kyoto / 京都常寂光寺",
    "Osaka / 大阪",
    "Ritsurin Park, Takamatsu / 高松栗林公園",
    "Kamakura / 鎌倉",
    "Hase Temple, Kamakura / 鎌倉長谷寺",
    "Amanohashidate, Kyoto-fu / 京都府天橋立",
    "Ochanomizu, Tokyo / 東京御茶ノ水",
    "Uji River / 宇治川",
    "Kankakei, Shodoshima / 小豆島寒霞渓",
    "Kyoto Tower / 京都タワー",
    "Kobe Harbour / 神戸港",
    "Akihabara, Tokyo / 東京秋葉原",
    "Enoden Train, Kamakura / 鎌倉江ノ電",
    "Ine boat house, Kyoto / 京都伊根船屋",
    "Baishinji Station, Matsuyama / 松山梅津寺駅",
    "Torii of Heian Jingu, Kyoto / 京都平安神宮の鳥居",
    "Dotonbori, Osaka / 大阪道頓堀",
    "Kenchoji, Kamakura / 鎌倉建長寺",
    "Tsurugaoka Kamakura / 鎌倉鶴岡",
    "Seto Naikai / 瀬戸内海",
    "Kurushima Kaikyo Ohashi, Imabari / 今治来島海峡大橋",
    "Asamayama, Karuizawa / 軽井沢浅間山",
]