var category = [
    {"id": "nature", "name": "山川"},
    {"id": "flowers", "name": "花祭"},
    {"id": "buildings", "name": "建物"},
    {"id": "transportation", "name": "鉄道"},
]

var photo = {
    "nature": [
        { "id": "p5", "desc": "Kamogawa, Kyoto / 京都鴨川" },
        { "id": "p48", "desc": "Kamogawa, Kyoto / 京都鴨川" },
        { "id": "p6", "desc": "Angel's Road, Shodoshima / 小豆島エンジェルロード" },
        { "id": "p11", "desc": "Seto Naikai / 瀬戸内海" },
        { "id": "p12", "desc": "Seto Naikai / 瀬戸内海" },
        { "id": "p17", "desc": "Kamakura / 鎌倉" },
        { "id": "p19", "desc": "Amanohashidate, Kyoto-fu / 京都府天橋立" },
        { "id": "p21", "desc": "Uji River / 宇治川" },
        { "id": "p22", "desc": "Kankakei, Shodoshima / 小豆島寒霞渓" },
        { "id": "p33", "desc": "Seto Naikai / 瀬戸内海" },
        { "id": "p35", "desc": "Asamayama, Karuizawa / 軽井沢浅間山" },
    ],
    "flowers": [
        { "id": "p2", "desc": "Kenchoji, Kamakura / 鎌倉建長寺" },
        { "id": "p4", "desc": "Tofukuji, Kyoto / 京都東福寺" },
        { "id": "p14", "desc": "Jojakkoji, Kyoto / 京都常寂光寺" },
        { "id": "p16", "desc": "Ritsurin Park, Takamatsu / 高松栗林公園" },
        { "id": "p31", "desc": "Kenchoji, Kamakura / 鎌倉建長寺" },
        { "id": "p32", "desc": "Tsurugaoka, Kamakura / 鎌倉鶴岡" },
        { "id": "p37", "desc": "Meguro River, Tokyo / 東京目黒川" },
    ],
    "buildings": [
        { "id": "p1", "desc": "Tokyo Tower / 東京タワー" },
        { "id": "p3", "desc": "Shinkyo Bridge, Nikko / 日光神橋" },
        { "id": "p7", "desc": "Shinjuku Gyoen, Tokyo / 東京新宿御苑" },
        { "id": "p8", "desc": "Byodoin, Uji / 宇治平等院" },
        { "id": "p45", "desc": "Byodoin, Uji / 宇治平等院" },
        { "id": "p9", "desc": "Tsutenya, Osaka / 大阪通天閣" },
        { "id": "p10", "desc": "Kasuga Taisha, Nara / 奈良春日大社" },
        { "id": "p13", "desc": "Tokyo / 東京" },
        { "id": "p15", "desc": "Osaka / 大阪" },
        { "id": "p18", "desc": "Hase Temple, Kamakura / 鎌倉長谷寺" },
        { "id": "p23", "desc": "Kyoto Tower / 京都タワー" },
        { "id": "p24", "desc": "Kobe Harbour / 神戸港" },
        { "id": "p25", "desc": "Akihabara, Tokyo / 東京秋葉原" }, 
        { "id": "p27", "desc": "Ine boat house, Kyoto / 京都伊根船屋" },
        { "id": "p29", "desc": "Torii of Heian Jingu, Kyoto / 京都平安神宮の鳥居" },
        { "id": "p30", "desc": "Dotonbori, Osaka / 大阪道頓堀" },
        { "id": "p34", "desc": "Kurushima Kaikyo Ohashi, Imabari / 今治来島海峡大橋" },
        { "id": "p36", "desc": "Toshogu, Nikko / 日光東照宮" },
        { "id": "p38", "desc": "Sensoji, Tokyo / 東京浅草寺" },
        { "id": "p39", "desc": "Kichijoji, Musashino / 武蔵野吉祥寺" },
        { "id": "p41", "desc": "Shinjuku, Tokyo / 東京新宿" },
        { "id": "p42", "desc": "Shinsaibashi, Osaka / 大阪心斎橋" },
        { "id": "p43", "desc": "Shinsekai Market, Osaka / 大阪新世界" },
        { "id": "p47", "desc": "Teramachi, Kyoto / 京都寺町" },
    ],
    "transportation": [
        { "id": "p20", "desc": "Ochanomizu, Tokyo / 東京御茶ノ水" },
        { "id": "p26", "desc": "Enoden Train, Kamakura / 鎌倉江ノ電" },
        { "id": "p28", "desc": "Baishinji Station, Matsuyama / 松山梅津寺駅" },
        { "id": "p40", "desc": "Keio Line, Kichijoji / 吉祥寺の京王線" },
        { "id": "p44", "desc": "Inside JR Nara Line / JR奈良線の列車の中" },
        { "id": "p46", "desc": "JR Kyoto Station / JR京都駅" },
    ],
}
